# Generated by Django 5.1.4 on 2024-12-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0002_alter_hotel_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_owner',
        ),
    ]
