# Generated by Django 5.1.4 on 2024-12-19 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_alter_hotelimage_hotel'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user_name', 'hotel')},
        ),
    ]
